{% set name = "flake8-return" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-return-{{ version }}.tar.gz
  sha256: 13a31edeb0c6157dd4f77166cdaa6141703d2b8b24def5558ae659852a003cb4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - flake8-plugin-utils >=1.0,<2.0
    - python >=3.6,<4.0

test:
  imports:
    - flake8_return
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flake8-return
  summary: Flake8 plugin that checks return values
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
